### ISSUE TITLE
Rooms not properly torn down on leave

### ISSUE THREAD

**Issue by Timendus** [Timendus/plumbing#19]
This bit:

https://github.com/Timendus/plumbing/blob/76698f7783017c6195edcc6e90016858f6803f4d/client/index.js#L34-L59

Attaches event handlers and starts the renderer each time we join a game. This is kinda-fine when we tear everything down again when we leave the game. We don't do that currently though, and it's a bit tricky to fix too.

So for now, if you open the same room three times, we start three render loops and receive chat messages three times 😕

**Comment by MinThaMie** [comment]
Rooms also don't seem to disappear when nobody is in them

**Comment by Timendus** [comment]
That should have been fixed
